config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: 'home#index'

  root to: 'home#index'

  resources :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord

  has_many :game_rounds, class_name: 'GameRoundDetail', dependent: :destroy
end

app/models/game_round_detail.rb
class GameRoundDetail < ApplicationRecord
  serialize :score_card, Array

  enum status: { 
                  started: 0, draw: 1, finished: 2
               }

  belongs_to :player1, class_name: 'User'
  belongs_to :player2, class_name: 'User'
  belongs_to :game
  belongs_to :winner, class_name: 'User', optional: true

  before_validation :set_status
  after_create_commit :update_users_detail

  validates_presence_of :status
  validate :check_players
  # validates_presence_of :winner, if: Proc.new{|a| a.status == 'finished'}
  validate :check_score_card, if: Proc.new {|a| !a.new_record? }
  validate :check_status

  def winner_user_list
    [
      [self.player1.name, self.player1_id],
      [self.player2.name, self.player2_id]
    ]
  end


  private

    def check_players
      errors.add :players_invalid, 'both player can not be same' if player2 == player1
    end

    def check_score_card
      errors.add :score_card, 'is invalid, Please enter valid scores' unless score_card.reject(&:empty?).size == 2 and !( winner.present? and score_card[0] == score_card[1] )
      errors.add :winner_invalid, 'select any' unless score_card[0] == score_card[1] or  winner.present?
    end

    def check_status
      errors.add :invalid_status, 'update valid status' if (score_card.present? or winner.present?) and status == 'started'
    end

    def set_status
      if self.new_record?
        self.status = 'started'
      elsif score_card[0].to_i == score_card[1].to_i
        self.status = 'draw'
      elsif winner.present?
        self.status = 'finished'
      end
      self.status
    end

    def update_users_detail
      self.player2.update_attributes(participation: (self.player2.participation + 1))
      self.player1.update_attributes(participation: (self.player1.participation + 1))
    end
end

app/models/user.rb
class User < ApplicationRecord

  validates_presence_of :name, :contact
  validates_uniqueness_of :contact

  def get_game_details
    participations = GameRoundDetail.where('player1_id or player2_id = ?', self.id)
    win = GameRoundDetail.where('winner_id = ?', self.id).count
    total_scores = participations.map{|a| a.player1_id == self.id ? a.score_card[0].to_i : a.score_card[1].to_i }.sum.to_f
    {total_scores: total_scores, avg_score: (total_scores/participations.count).round(2), win: win, loose: (participations.count - win).abs }
  end

  def highest_score_detail
    participations = GameRoundDetail.where('player1_id or player2_id = ?', self.id)
    detail = Hash.new
    participations.each do |participation|
      score = participation.player1_id == self.id ? participation.score_card[0] : participation.score_card[1]
      if detail[:top_score].to_i < score.to_i
        detail[:top_score] = score.to_i
        detail[:game_name] = participation.game.name
        detail[:opponent] = participation.player1_id == self.id ? participation.player2.name : participation.player1.name
      end
    end
    detail
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_round_details_controller.rb
class GameRoundDetailsController < InheritedResources::Base

  private

    def game_round_detail_params
      params.require(:game_round_detail).permit(:player1_id, :palyer2_id, :winner_id, :status)
    end

end

app/controllers/games_controller.rb
class GamesController < InheritedResources::Base

  private

    def game_params
      params.require(:game).permit(:name)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @users = User.where("participation >= 10").sort{|a| a.get_game_details[:avg_score]}.first(10)
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  def index
    @users = User.all  
  end

  def show
    @user = User.find(params[:id])
  end


  private

    def user_params
      params.require(:user).permit(:name, :contact)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_round_details_helper.rb
module GameRoundDetailsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/game_round_details/_form.html.erb
<%= form_with(model: game_round_detail, local: true) do |form| %>
  <% if game_round_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game_round_detail.errors.count, "error") %> prohibited this game_round_detail from being saved:</h2>

      <ul>
        <% game_round_detail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :player1_id %>
    <%= form.text_field :player1_id %>
  </div>

  <div class="field">
    <%= form.label :palyer2_id %>
    <%= form.text_field :palyer2_id %>
  </div>

  <div class="field">
    <%= form.label :winner_id %>
    <%= form.text_field :winner_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/game_round_details/edit.html.erb
<h1>Editing Game Round Detail</h1>

<%= render 'form', game_round_detail: @game_round_detail %>

<%= link_to 'Show', @game_round_detail %> |
<%= link_to 'Back', game_round_details_path %>

app/views/game_round_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Game Round Details</h1>

<table>
  <thead>
    <tr>
      <th>Player1</th>
      <th>Palyer2</th>
      <th>Winner</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_round_details.each do |game_round_detail| %>
      <tr>
        <td><%= game_round_detail.player1_id %></td>
        <td><%= game_round_detail.palyer2_id %></td>
        <td><%= game_round_detail.winner_id %></td>
        <td><%= game_round_detail.status %></td>
        <td><%= link_to 'Show', game_round_detail %></td>
        <td><%= link_to 'Edit', edit_game_round_detail_path(game_round_detail) %></td>
        <td><%= link_to 'Destroy', game_round_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game Round Detail', new_game_round_detail_path %>

app/views/game_round_details/new.html.erb
<h1>New Game Round Detail</h1>

<%= render 'form', game_round_detail: @game_round_detail %>

<%= link_to 'Back', game_round_details_path %>

app/views/game_round_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player1:</strong>
  <%= @game_round_detail.player1_id %>
</p>

<p>
  <strong>Palyer2:</strong>
  <%= @game_round_detail.palyer2_id %>
</p>

<p>
  <strong>Winner:</strong>
  <%= @game_round_detail.winner_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @game_round_detail.status %>
</p>

<%= link_to 'Edit', edit_game_round_detail_path(@game_round_detail) %> |
<%= link_to 'Back', game_round_details_path %>

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/home/index.html.erb
<h1>DashBoard</h1>

<h4>Top 10 user List</h4>

<p>A leader board screen to list the members with the top 10 average scores, for those
members who have played at least 10 matches.</p>
<% if @users.present? %>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Avg. Score</th>
          <th></th>
        </tr>
      </thead>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= user.name %>
          </td>
          <td>
            <%= user.get_game_details[:avg_score] %>
          </td>
          <td>
            <%= link_to 'Show', user_path(user) %>
          </td>
        </tr>
      <% end %>
    </table>
<% else %>
  <h5>No user avaiable</h5>
<% end %>

<%= link_to "Users List", users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScrabbleClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.text_field :contact %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.contact %></td>
        <td><%= link_to 'Show', user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Top users list", dashboard_path %>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Contact:</strong>
  <%= @user.contact %>
</p>
<p>
  <strong>Win:</strong>
  <%= @user.get_game_details[:win] %>
</p>
<p>
  <strong>Looses:</strong>
  <%= @user.get_game_details[:loose] %>
</p>
<p>
  <strong>Avg. Score:</strong>
  <%= @user.get_game_details[:avg_score] %>
</p>

<p>
  <strong>Highest score:</strong>
  <%= @user.highest_score_detail[:top_score] %>
</p>
<p>
  <strong>Game:</strong>
  <%= @user.highest_score_detail[:game_name] %>
</p>
<p>
  <strong>Opponent:</strong>
  <%= @user.highest_score_detail[:opponent] %>
</p>

<%= link_to 'Users list', users_path %>